package org.bonitasoft.example

import org.bonitasoft.engine.api.APIClient
import org.bonitasoft.engine.page.PageCreator
import java.nio.file.Files
import java.nio.file.Paths
import java.util.function.Consumer

class DeployPage(val pageName: String, val type: String) : Consumer<APIClient> {
    override fun accept(apiClient: APIClient) {
        apiClient.customPageAPI.createPage(PageCreator(pageName, "custom_form.zip").apply {
            setContentType(type)
            setDescription("This is a form generated using the bonita-test-processes, an awesome project")
            setDisplayName("GeneratedForm $pageName")
        }, Files.readAllBytes(Paths.get(DeployPage::class.java.getResource("/case-autogenerated-overview.zip").toURI())))
    }
}